name: Download and Commit RSS Feed

on:
  schedule:
    # This will run every day at 00:00 UTC. You can adjust the cron schedule as needed.
    - cron: '0 0 * * *'
  workflow_dispatch: # This enables manual triggering of the workflow.

jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download RSS Feed
      run: |
        curl -o rss_feed.xml https://www.reddit.com/r/gamedesign/.rss

    - name: Commit and Push if it's updated
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add rss_feed.xml
        git commit -m "Updated RSS feed" || exit 0  # This will not fail if there's nothing to commit
        git push
